.PHONY: all
all:
	make -C pci
	make -C ixgbe
	make -C membdev
	make -C nvme
	make -C tpm

.PHONY: clean
clean:
	make -C pci clean
	make -C ixgbe clean
	make -C membdev clean
	make -C nvme clean
	make -C tpm clean
