[package]
name = "virtio_net_mmio"
version = "0.1.0"
authors = ["RedLeaf Team"]
edition = "2018"

[dependencies]
libsyscalls = { path = "../../../../lib/core/libsyscalls" }
libtime = { path = "../../../../lib/core/libtime" }
console = { path = "../../../../lib/core/console" }
malloc = { path = "../../../../lib/core/malloc" }
libbenchnet = { path = "../../../lib/libbenchnet" }
spin = { path = "../../../../lib/core/spin-rs" }

smolnet = { path = "../../../../domains/lib/smolnet" }
hashbrown = "0.7.2"
redhttpd = { path = "../../../lib/redhttpd" }

virtio_device = { path = "../../../../lib/devices/virtio" }
virtio_network_device = { path = "../../../../lib/devices/virtio_net" }

# Interfaces
syscalls = { path = "../../../../lib/core/interfaces/syscalls" }
pci_driver = { path = "../../../../lib/core/interfaces/dev/pci/pci_driver" }
protocol = { path = "../../../../lib/core/interfaces/protocol" }
platform = { path = "../../../../lib/core/interfaces/platform" }
interface = { path = "../../../../interface/generated" }


[dependencies.smoltcp]
path = "../../../../lib/external/smoltcp"
default-features = false
features = ["alloc", "proto-ipv4", "socket-tcp", "socket-icmp", "ethernet"]

[features]
default = [
]

virtio_net = []
