use FooSys;

struct FooStruct {
    a: u32;
    b: bool;
}

pub trait BDev {
    fn add_sys(sys: RRef<dyn FooSys::Syscalls>);
    fn read(&self, block: u32, data: RRef<FooStruct>) -> RRef<FooStruct>;
    fn write(&self, block: u32, data: RRef<FooStruct>);
}