.PHONY: all
all:
	make -C dom_a
	make -C dom_b
	make -C dom_c
	make -C dom_d
	make -C shadow
.PHONY: clean
clean:
	make -C dom_a clean
	make -C dom_b clean
	make -C dom_c clean
	make -C dom_d clean
	make -C shadow clean
