[package]
name = "ahci"
version = "0.1.0"
authors = ["Redleaf team <aburtsev@uci.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syscalls = { path = "../../../../lib/core/interfaces/syscalls" }
libsyscalls = { path = "../../../../lib/core/libsyscalls" }
libtime = { path = "../../../../lib/core/libtime" }
console = { path = "../../../../lib/core/console" }
libbenchnvme = { path = "../../../lib/libbenchnvme" }
malloc = { path = "../../../../lib/core/malloc" }
spin = "0.5.2"
bitflags = "1.0.4"
byteorder = { version = "1.2", default-features = false }
serde_derive = "1.0.101"
ahci_regs = { path = "../../../../lib/core/interfaces/dev/ahci"}
ahci_device = { path = "../../../../lib/devices/ahci" }
pci_driver = { path = "../../../../lib/core/interfaces/dev/pci/pci_driver" }
interface = { path = "../../../../interface/generated" }
protocol = { path = "../../../../lib/core/interfaces/protocol" }
platform = { path = "../../../../lib/core/interfaces/platform" }
libdma = { path = "../../../../lib/devices/libdma" }
rref = { path = "../../../../lib/core/rref" }
b2histogram = "1.0"
array-init = "0.1.1"